#DØR
- alias: DoorOpen
  trigger:
    platform: state
    entity_id: sensor.sensative_strips_access_control
    from: '22'
    to: '23'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.pk
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.trine
      state: 'not_home'
  action:
    service: notify.pk
    data_template:
      title: "Dør endret"
      message: "Døren er {% if is_state('sensor.sensative_strips_access_control', '22') %}åpen{% else %}lukket{% endif %}!"

- alias: DoorClosed
  trigger:
    platform: state
    entity_id: sensor.sensative_strips_access_control
    from: '23'
    to: '22'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.pk
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.trine
      state: 'not_home'
  action:
    service: notify.pk
    data_template:
      title: "Dør endret"
      message: "Døren er {% if is_state('sensor.sensative_strips_access_control', '22') %}åpen{% else %}lukket{% endif %}!"

#BEVEGELSE LYS
- alias: Kjellerlys, på
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.bevegelse_kjeller
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.bryter1_kjeller
    - service: notify.pk
      data_template:
        title: "Lys"
        message: "Skrur PÅ kjellerlys"

- alias: Kjeller lys, av
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.bevegelse_kjeller
    to: 'off'
    for:
      minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.bryter1_kjeller
    - service: notify.pk
      data_template:
        title: "Lys"
        message: "Skrur AV kjellerlys"
