- id: '1575925513204'
  alias: Nattmodus p책 automasjon
  description: ''
  trigger:
  - entity_id: input_boolean.nattmodus_hoved
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - device_id: 286e634e0ab64cc0b6a1cc831f8fd508
    domain: switch
    entity_id: switch.fibaro_system_fgwpe_f_wall_plug_gen5_switch_2
    type: turn_off
  - device_id: 278210ddb582492484a6b6be81596f2c
    domain: switch
    entity_id: switch.fibaro_system_fgwpe_f_wall_plug_gen5_switch
    type: turn_off
- id: '1576005670987'
  alias: Nattmodus av automasjon
  description: ''
  trigger:
  - entity_id: input_boolean.nattmodus_hoved
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - device_id: 286e634e0ab64cc0b6a1cc831f8fd508
    domain: switch
    entity_id: switch.fibaro_system_fgwpe_f_wall_plug_gen5_switch_2
    type: turn_on
  - device_id: 278210ddb582492484a6b6be81596f2c
    domain: switch
    entity_id: switch.fibaro_system_fgwpe_f_wall_plug_gen5_switch
    type: turn_on
- id: '1577953454376'
  alias: Varsle om skap
  description: ''
  trigger:
  - entity_id: binary_sensor.telldus_tzdw_100_magnet_switch_sensor_2
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Skapet er 책pnet
      title: Skap 책pnet
    service: notify.pk
- id: '1578336737649'
  alias: Skifte farge i kjelleren
  description: ''
  trigger:
  - device_id: 96c2cfa301aa4bae8450ba1f8e0c30c6
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_long_press
  condition: []
  action:
  - alias: ''
    data: {}
    entity_id: input_select.pyntelampe_color
    service: input_select.select_next
  - data_template:
      color_name: '{{ states.input_select.pyntelampe_color.state }}'
      entity_id: light.light_23
    service: light.turn_on
- id: '1581111122144'
  alias: Fjernkontroll lys isabell nattlys p책
  description: ''
  trigger:
  - event_data:
      entity_id: zwave.nodon_id_rf_crc_3_6_0x_soft_remote
      scene_id: 10
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - device_id: 1067078dc6844073ad8966902a7ce2a3
    domain: light
    entity_id: light.nattlys_isabell
    type: turn_on
- id: '1581112405699'
  alias: Fjernkontroll lys isabell nattlys av
  description: ''
  trigger:
  - event_data:
      entity_id: zwave.nodon_id_rf_crc_3_6_0x_soft_remote
      scene_id: 30
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - device_id: 1067078dc6844073ad8966902a7ce2a3
    domain: light
    entity_id: light.nattlys_isabell
    type: turn_off
- id: '1581112955512'
  alias: Fjernkontroll lys isabell nattlys opp
  description: ''
  trigger:
  - event_data:
      entity_id: zwave.nodon_id_rf_crc_3_6_0x_soft_remote
      scene_id: 12
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data_template:
      brightness: '{{ states.light.nattlys_isabell.attributes.brightness + 50 }}'
    entity_id: light.nattlys_isabell
    service: light.turn_on
- id: '1581113175285'
  alias: Fjernkontroll lys isabell nattlys ned
  description: ''
  trigger:
  - event_data:
      entity_id: zwave.nodon_id_rf_crc_3_6_0x_soft_remote
      scene_id: 32
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data_template:
      brightness: '{{ states.light.nattlys_isabell.attributes.brightness - 50 }}'
    entity_id: light.nattlys_isabell
    service: light.turn_on
- id: '1581113702651'
  alias: Fjernkontroll lys isabell nattlys nullstill
  description: ''
  trigger:
  - event_data:
      entity_id: zwave.nodon_id_rf_crc_3_6_0x_soft_remote
      scene_id: 13
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.nattlys_isabell
      rgb_color:
      - 204
      - 0
      - 102
    service: light.turn_on
  - data:
      brightness: 1
      entity_id:
      - light.nattlys_isabell
      transition: 10
    service: light.turn_on
- id: '1581114331457'
  alias: Fjernkontroll lys isabell nattlys lesing
  description: ''
  trigger:
  - event_data:
      entity_id: zwave.nodon_id_rf_crc_3_6_0x_soft_remote
      scene_id: 33
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
  - data:
      brightness: 255
      entity_id:
      - light.nattlys_isabell
      transition: 5
    service: light.turn_on
  - data:
      entity_id: light.nattlys_isabell
      rgb_color:
      - 255
      - 255
      - 255
    service: light.turn_on
