- platform: nmap_tracker
  hosts: 192.168.1.0/24
  home_interval: 10
  interval_seconds: 10
  consider_home: 180
  new_device_defaults:
    track_new_devices: true
    hide_if_away: false


- platform: tplink
  host: 192.168.1.1
  username: !secret router_username
  password: !secret router_password
  interval_seconds: 10
  consider_home: 180
  track_new_devices: yes