title: The Solheim/Johanssons

resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:

  - icon: mdi:home-assistant
    title: Hoved
    id: hoved
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - id: a7f59ab744984d7e932ebac9bd193565  # Automatically created id
        type: entities
        title: Nattmodus
        show_header_toggle: true
        entities:
          - type: call-service
            icon: mdi:power
            name: Oppe
            action_name: Velg
            service: script.nattmodus_oppe_toggle
      - id: ce21d66b8cdb426085b0063d97b0c98c  # Automatically created id
        type: entity-button
        entity: light.stue
      - id: 932ec73ca9c44367bca7d511667cad36  # Automatically created id
        type: entity-button
        entity: light.gang
      - id: 2a3b1b9b969246fc9a253e86ed18e271  # Automatically created id
        type: entity-button
        entity: light.gangoppe

  - title: Varme
    id: varme
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - id: 281b7b00e9574e69a9e9feb70b8817e4  # Automatically created id
        type: thermostat
        entity: climate.stue_varme
      - id: 1a4247d49c0b4d529b7b5fe5e3a08e22  # Automatically created id
        type: thermostat
        entity: climate.kjeller_varme
      - id: f6e839943f1547318201d5662918dda4  # Automatically created id
        type: entities
        title: Temperaturer
        show_header_toggle: false
        entities:
          - input_number.ferie_temperatur
          - input_number.kjeller_hjemmekontor_temperatur
          - input_number.kjeller_normal_temperatur
          - input_number.stue_morgen_temperatur
          - input_number.stue_dagtid_temperatur
          - input_number.stue_ettermiddag_temperatur
          - input_number.stue_natt_temperatur
      - id: 617c58edfd624d3e8a1e7f6630a5a3e5  # Automatically created id
        type: entities
        title: Moduser
        show_header_toggle: false
        entities:
          - input_boolean.ferie_modus
          - input_boolean.hjemmekontor_modus
      - id: 19a6c5c3ab684161ab39eea0175b12a1  # Automatically created id
        type: entities
        title: Termostat
        entities:
          - climate.stue_varme
          - climate.kjeller_varme

  - title: Lys
    id: lys
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: entities
        id: 47a400f2d8844a0ea66610bb82809ac7  # Automatically created id
        title: Lys
        entities:
          - light.stue
          - light.gang
          - light.pyntelampe
          - light.sofa
          - light.gangoppe
        show_header_toggle: false
      - type: entities
        id: 8a2947ff2ece48b48696eada13224513  # Automatically created id
        title: Julelys
        entities:
          - switch.ekstra_bryter
        show_header_toggle: false
      - type: entities
        id: d7967c563d2146fb989a336122431190  # Automatically created id
        title: Fluxer
        entities:
          - switch.fluxer_mired
          - switch.fluxer_xy
        show_header_toggle: false
