title: The Solheim/Johanssons

resources:
- url: /local/my-custom-card.js
  type: js
- url: /local/my-webfont.css
  type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
- weblink.router
views:
# View tab title.
- icon: mdi:home-assistant
  title: Hoved
  # Optional unique id for direct access /lovelace/${id}
  id: example
  # Optional background (overwrites the global background).
  background: radial-gradient(crimson, skyblue)
  # Each view can have a different theme applied. Theme should be defined in the frontend.
  theme: dark-mode
  # The cards to show on this view.
  cards:
  # The filter card will filter entities for their state
  - type: entity-filter
    entities:
    - device_tracker.galaxys8
    - device_tracker.trine
    - device_tracker.ekstratelefonen
    state_filter:
    - 'home'
    card:
      type: glance
      title: Hvem er hjemme

    # The picture entity card will represent an entity with a picture
  - type: picture-entity
    image: https://www.home-assistant.io/images/default-social.png
    entity: light.bed_light

  - type: entities
    title: Termostat
    entities:
    - climate.stue_varme
    - climate.kjeller_varme

- title: Second view
  cards:
  - type: entities
    title: Example
    entities:
    - entity: group.stue_varme
      name: Stue varme


- icon: mdi:settings
  title: Innstillinger
  cards:
  - type: entities
    title: Lovelace
    entities:
    - light.kitchen

- title: Lys
  cards:
  - type: entities
    title: Lovelace
    entities:
    - light.kitchen

- title: Varme
  cards:
  - type: entities
    title: Lovelace
    entities:
    - light.kitchen
