title: The Solheim/Johanssons

resources:
- url: /local/my-custom-card.js
  type: js
- url: /local/my-webfont.css
  type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
- weblink.router
views:

- icon: mdi:home-assistant
  title: Hoved
  id: example
  background: radial-gradient(crimson, skyblue)
  theme: dark-mode
  cards:

  - type: entities
    title: Nattmodus
    show_header_toggle: true
    entities:
    - type: call-service
      icon: mdi:power
      name: Oppe
      action_name: Velg
      service: script.nattmodus_toggle
    - type: divider
    - type: weblink
      name: Home Assistant
      url: https://www.home-assistant.io/
      icon: mdi:home-assistant

  - type: entities
    title: Termostat
    entities:
    - climate.stue_varme
    - climate.kjeller_varme

- title: Varme
  cards:
  - type: entities
    title: Første etasje varme
    show_header_toggle: false
    entities:
    - entity: group.stue_varme
      name: Alle
    - switch.varme1_stue
    - switch.varme2_stue
    - switch.varme_kjokken
  - type: entities
    title: Temperaturer
    show_header_toggle: false
    entities:
    - input_number.ferie_temperatur
    - input_number.kjeller_hjemmekontor_temperatur
    - input_number.kjeller_normal_temperatur
    - input_number.stue_morgen_temperatur
    - input_number.stue_dagtid_temperatur
    - input_number.stue_ettermiddag_temperatur
    - input_number.stue_natt_temperatur
  - type: entities
    title: Moduser
    show_header_toggle: false
    entities:
    - input_boolean.ferie_modus
    - input_boolean.hjemmekontor_modus
  - type: entities
    title: Termostat
    entities:
    - climate.stue_varme
    - climate.kjeller_varme
  - type: history-graph
    title: 'Temperatur'
    entities:
    - history_graph.temperatur_siste_48_timer

- title: Lys
  cards:
  - type: entities
    title: Lys
    entities:
    - light.stue
    - light.gang
    - light.pyntelampe
    - light.sofa
    - light.gangoppe
  - type: entities
    title: Julelys
    entities:
    - switch.ekstra_bryter
  - type: entities
    title: Fluxer
    entities:
    - switch.fluxer_mired
    - switch.fluxer_xy

