- platform: template
  sensors:
    door_open:
      friendly_name: "Dørsensor"
      device_class: opening
      value_template: "{{ is_state('sensor.sensative_strips_access_control', '22') }}"

- platform: template
  sensors:
    bevegelse_hoveetasje:
      friendly_name: "Bevegelse i hovedetasjen"
      device_class: motion
      entity_id:
      - binary_sensor.bevegelse_gang
      - binary_sensor.bevegelse_stue
      value_template: >-
        {% if is_state('binary_sensor.bevegelse_gang', 'on')
           or is_state('sensor.bevegelse_stue', 'on') %}
           true
        {% else %}
           false
        {% endif %}