#- platform: flux
#  lights:
#  - light.spisebord
#  - light.sofa
#  name: Fluxer
#  start_time: '6:00'
#  stop_time: '23:00'
#  start_colortemp: 4000
#  sunset_colortemp: 3900
#  stop_colortemp: 2200
#  disable_brightness_adjust: True
#  mode: mired
#  transition: 30
#  interval: 60

- platform: flux
  lights:
  - light.spisebord
  - light.sofa
  name: Fluxer
  start_time: '6:00'
  stop_time: '23:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  brightness: 200
  disable_brightness_adjust: True
  mode: xy
  transition: 30
  interval: 60