switch:
- platform: flux
  lights:
  - light.stue
  name: Fluxer
  start_time: '6:00'
  stop_time: '23:00'
  start_colortemp: 4000
  sunset_colortemp: 3900
  stop_colortemp: 2200
  disable_brightness_adjust: True
  mode: mired
  transition: 30
  interval: 60