- platform: template
  switches:
    nattmodus_oppe:
      value_template: "{{ is_state('input_boolean.nattmodus_oppe', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: script.nattmodus_oppe_pa
      turn_off:
        service: switch.turn_on
        data:
          entity_id: script.nattmodus_oppe_pa