- platform: generic_thermostat
  name: 'Stue varme'
  heater: group.stue_varme
  target_sensor: sensor.temperatur_stue
  min_temp: 12
  max_temp: 25
  ac_mode: False
  target_temp: 22
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes: 60
  initial_operation_mode: "on"
  away_temp: 17