- platform: generic_thermostat
  name: 'Stue varme'
  heater: group.stue_varme
  target_sensor: sensor.temperatur_gang
  min_temp: 12
  max_temp: 25
  target_temp: 22
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes: 60
  initial_hvac_mode: "auto"
  away_temp: 17

- platform: generic_thermostat
  name: 'Kjeller varme'
  heater: group.kjeller_varme
  target_sensor: sensor.temperatur_kjeller
  min_temp: 12
  max_temp: 25
  target_temp: 15
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes: 60
  initial_hvac_mode: "auto"
  away_temp: 15