- platform: generic_thermostat
  name: Stue_varme
  heater: group.stue_varme
  target_sensor: sensor.temperatur_gang
  min_temp: 12
  max_temp: 25
  target_temp: 22
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes: 60
  initial_hvac_mode: "heat"
  away_temp: 17

- platform: generic_thermostat
  name: Kjeller_varme
  heater: switch.varme1_kjeller
  target_sensor: sensor.temperatur_kjeller
  min_temp: 12
  max_temp: 25
  target_temp: 15
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes: 60
  initial_hvac_mode: "heat"
  away_temp: 15