- alias: 'Toggle lamp from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: fjernkontroll1
      event: 1002
  action:
  - service: light.toggle
    entity_id: light.hvitdimmbar1
