- alias: 'Toggle lamp from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: fjernkontroll1
      event: 1002
    action:
    - service: light.toggle
      entity_id: light.hvitdimmbar1
    - service: light.toggle
        entity_id: light.ambientdimmbar1

- alias: 'Increase brightness of lamp from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: fjernkontroll1
      event: 2002
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.hvitdimmbar1
      brightness: >
        {% set bri = states.light.hvitdimmbar1.attributes.brightness | int %}
        {{ [bri+30, 249] | min }}
  - service: light.turn_on
      data_template:
        entity_id: llight.ambientdimmbar1
        brightness: >
          {% set bri = states.light.ambientdimmbar1.attributes.brightness | int %}
          {{ [bri+30, 249] | min }}

- alias: 'Decrease brightness of lamp from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: fjernkontroll1
      event: 3002
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.hvitdimmbar1
      brightness: >
        {% set bri = states.light.hvitdimmbar1.attributes.brightness | int %}
        {{ [bri-30, 0] | max }}
  - service: light.turn_on
    data_template:
      entity_id: light.ambientdimmbar1
      brightness: >
        {% set bri = states.light.ambientdimmbar1.attributes.brightness | int %}
        {{ [bri-30, 0] | max }}