- alias: "Garasjen er apen"
  trigger:
    platform: state
    entity_id: binary_sensor.garage_open
  action:
    - service: notify.pk
      data_template:
        title: "Garasjen er {% if is_state('binary_sensor.garage_open', 'off') %}IKKE{% endif %} 책pen!"
        message: "Garasjen er {% if is_state('binary_sensor.garage_open', 'off') %}IKKE{% endif %} 책pen!"
    - service: notify.tv
      data_template:
        title: "Garasjen er {% if is_state('binary_sensor.garage_open', 'off') %}IKKE{% endif %} 책pen!"
        message: "Garasjen er {% if is_state('binary_sensor.garage_open', 'off') %}IKKE{% endif %} 책pen!"