#- alias: 'Halloween skifte farge'
#  initial_state: False
#  hide_entity: False
#  trigger:
#    platform: time
#    seconds: '/5'
#  condition:
#  - condition: state
#    entity_id: input_boolean.halloween_modus
#    state: 'on'
#  action:
#    service: homeassistant.turn_on
#    entity_id:
#    - light.pyntelampe
#    data:
#      effect: random
#      transition: 1
#      brightness: 255


- alias: 'Halloween skifte farge'
  trigger:
    platform: time
    seconds: /15
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.pyntelampe
      state: 'on'
    - condition: state
      entity_id: input_boolean.halloween_modus
      state: 'on'
  action:
  - service: script.change_pyntelampe

- alias: 'Halloween blinke lys'
  trigger:
    platform: state
    entity_id: binary_sensor.door_open
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.halloween_modus
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.light_flash

- alias: 'Halloween blinke lys av'
  trigger:
    platform: state
    entity_id: binary_sensor.door_open
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.halloween_modus
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.light_flash_cancel