- alias: Kjellerlys, på
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.bevegelse_kjeller
    to: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.bryter1_kjeller

- alias: Kjeller lys, av
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.bevegelse_kjeller
    to: 'off'
    for:
      minutes: 10
  action:
  - service: switch.turn_off
  entity_id: switch.bryter1_kjeller
