- alias: Utelys pa, solnedgang
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    entity_id: light.garage
    service: light.turn_on
#
#- alias: Utelys av, soloppgang
#  initial_state: true
#  trigger:
#  - event: sunrise
#    offset: 00:30:00
#    platform: sun
#  action:
#  - data:
#    entity_id: light.garage
#    service: light.turn_off