- alias: Lys hovedetasje, på bevegelse
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.bevegelse_stue
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.stue
  - service: light.turn_on
    entity_id: light.gang
