- alias: Utelys pa, solnedgang
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: "-00:20:00"
  action:
    entity_id: light.ute
    service: light.turn_on

- alias: Utelys av, soloppgang
  initial_state: true
  trigger:
    platform: sun
    event: sunrise
    offset: "00:30:00"
  action:
    entity_id: light.ute
    service: light.turn_off