- alias: Kjellerlys, på
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.bevegelse_kjeller
    to: 'on'
  condition:
  - condition: state
    entity_id: light.kjeller
    state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.kjeller
      brightness: 255
      kelvin: 2700

- alias: Kjeller lys, av
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.bevegelse_kjeller
    to: 'off'
    for:
      minutes: 10
  action:
  - service: light.turn_off
    entity_id: light.kjeller
