- alias: 'Lys stue on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch
      event: 1002
  action:
  - service: light.turn_on
    entity_id: light.stue
  - service: light.turn_on
    entity_id: light.gang

- alias: 'Lys stue off'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch
      event: 4002
  action:
  - service: light.turn_off
    entity_id: light.stue
  - service: light.turn_off
    entity_id: light.gang

- alias: 'Lys stue dimme opp'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch
      event: 2002
  action:
  - service: light.turn_on
    data:
      entity_id: light.stue
      brightness_step_pct: 5
  - service: light.turn_on
    data:
      entity_id: light.gang
      brightness_step_pct: 5

- alias: 'Lys stue dimme ned'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch
      event: 3002
  action:
  - service: light.turn_on
    data:
      entity_id: light.stue
      brightness_step_pct: -5
  - service: light.turn_on
    data:
      entity_id: light.gang
      brightness_step_pct: -5

- alias: 'Lys stue bytte farge'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch
      event: 2001
  action:
  - service: input_select.select_next
    data:
      entity_id: input_select.pyntelampe_color
  - service: light.turn_on
    data_template:
      entity_id: light.pyntelampe
      color_name: '{{ states.input_select.pyntelampe_color.state }}'
