- alias: Lys hovedetasje, på bevegelse
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.bevegelse_stue
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.stue
  - service: light.turn_on
    entity_id: light.gang


##TODO
# Akrtvere en nattmodus for førsteetasje
# VEd bevegelse i nattmodus bare skru på lysene litt. (MEd mindre døra åpnes?)
# Skru på gang-lyset om det er bevegelse i gangen (og allt lyset om et er bevegelse i stua?)