- alias: "Kjellerlys, på bevegelse"
  trigger:
    platform: state
    entity_id: binary_sensor.bevegelse_kjeller
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: light.kjeller_2
      state: 'off'
    - condition: state
      entity_id: input_boolean.kjeller_lights_dimmed_auto
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.kjeller_2
      brightness: 255
      kelvin: 2700
  - service: input_boolean.turn_on
    entity_id: input_boolean.kjeller_lights_on_auto
  - service: input_boolean.turn_off
    entity_id: input_boolean.kjeller_lights_dimmed_auto

- alias: "Kjellerlys, dimmet bevegelse"
  trigger:
    platform: state
    entity_id: binary_sensor.bevegelse_kjeller
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.kjeller_2
      state: 'on'
    - condition: state
      entity_id: input_boolean.kjeller_lights_on_auto
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.kjeller_2
      brightness: 50
      kelvin: 2700
  - service: input_boolean.turn_on
    entity_id: input_boolean.kjeller_lights_dimmed_auto

- alias: "Kjellerlys, av ingen bevegelse"
  trigger:
    platform: state
    entity_id: binary_sensor.bevegelse_kjeller
    to: 'off'
    for:
      minutes: 15
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.kjeller_2
      state: 'on'
    - condition: state
      entity_id: input_boolean.kjeller_lights_on_auto
      state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.kjeller_2
  - service: input_boolean.turn_off
    entity_id: input_boolean.kjeller_lights_on_auto
  - service: input_boolean.turn_off
    entity_id: input_boolean.kjeller_lights_dimmed_auto

- alias: "Kjellerlys skrudd av"
  trigger:
  - platform: state
    entity_id: light.kjeller_2
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.kjeller_lights_on_auto
    state: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.kjeller_lights_on_auto
  - service: input_boolean.turn_off
    entity_id: input_boolean.kjeller_lights_dimmed_auto