- alias: 'Lys kjeller on/off'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: fjernkontroll2
      event: 1002
  action:
  - service: light.toggle
    entity_id: light.kjeller_2

- alias: 'Lys kjeller dimme opp'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: fjernkontroll2
      event: 2002
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.kjeller_2
      brightness: >
        {% set bri = states.light.kjeller_2.attributes.brightness | int %}
        {{ [bri+30, 254] | min }}

- alias: 'Lys kjeller dimme ned'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: fjernkontroll2
      event: 3002
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.kjeller_2
      brightness: >
        {% set bri = states.light.kjeller_2.attributes.brightness | int %}
        {{ [bri-100, 0] | max }}

- alias: 'Lys kjeller varme opp'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: fjernkontroll2
      event: 4002
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.kjeller
      color_temp: >
        {% set kel = states.light.kjeller_2.attributes.color_temp | int %}
        {{ [kel+50, 500] | min }}

- alias: 'Lys kjeller varme ned'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: fjernkontroll2
      event: 5002
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.kjeller_2
      color_temp: >
        {% set kel = states.light.kjeller_2.attributes.color_temp | int %}
        {{ [kel-50, 153] | max }}