- alias: 'Lys stue on'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: fjernkontroll1
      event: 1002
  action:
  - service: light.turn_on
    entity_id: light.stue
    brightness: 255
#
#- alias: 'Lys stue off'
#  initial_state: 'on'
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: fjernkontroll1
#      event: 4002
#  action:
#  - service: light.turn_off
#    entity_id: light.stue

#- alias: 'Lys stue dimme opp'
#  initial_state: 'on'
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: fjernkontroll1
#      event: 2002
#  action:
#  - service: light.turn_on
#    data_template:
#      entity_id: light.spisebord
#      brightness: >
#        {% set bri = states.light.spisebord.attributes.brightness | int %}
#        {{ [bri+30, 249] | min }}
#  - service: light.turn_on
#    data_template:
#      entity_id: light.sofakrok1
#      brightness: >
#        {% set bri = states.light.sofakrok1.attributes.brightness | int %}
#        {{ [bri+30, 249] | min }}
#
#- alias: 'Lys stue dimme ned'
#  initial_state: 'on'
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: fjernkontroll1
#      event: 3002
#  action:
#  - service: light.turn_on
#    data_template:
#      entity_id: light.stue
#      brightness: >
#        {% set bri = states.light.spisebord.attributes.brightness | int %}
#        {{ [bri-30, 0] | max }}
#  - service: light.turn_on
#    data_template:
#      entity_id: light.sofakrok1
#      brightness: >
#        {% set bri = states.light.sofakrok1.attributes.brightness | int %}
#        {{ [bri-30, 0] | max }}