- alias: nattlys av hverdag hverdag
  trigger:
  - platform: time
    at: '06:15:00'
  - platform: homeassistant
    event: start
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.workday_today
      state: 'on'
    - condition: state
      entity_id: input_boolean.nattlys_vekketid_custom
      state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.nattlys_isabell
      brightness: 2
      transition: 10
      rgb_color: [102,204,0]
  - service: light.turn_on
    data:
      entity_id: light.nattlys_aleksander
      brightness: 2
      transition: 10
      rgb_color: [102,204,0]

- alias: nattlys av helg
  trigger:
  - platform: time
    at: '06:30:00'
  - platform: homeassistant
    event: start
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.workday_today
      state: 'off'
    - condition: state
      entity_id: input_boolean.nattlys_vekketid_custom
      state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.nattlys_isabell
      brightness: 2
      transition: 10
      rgb_color: [102,204,0]
  - service: light.turn_on
    data:
      entity_id: light.nattlys_aleksander
      brightness: 2
      transition: 10
      rgb_color: [102,204,0]

- alias: nattlys av custom
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.nattlys_vekketid.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.nattlys_vekketid_custom
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.nattlys_isabell
      brightness: 2
      transition: 10
      rgb_color: [102,204,0]
  - service: light.turn_on
    data:
      entity_id: light.nattlys_aleksander
      brightness: 2
      transition: 10
      rgb_color: [102,204,0]

- alias:  Nattmodus oppe av
  initial_state: True
  trigger:
  - platform: time
    at: '08:00:00'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.nattmodus_oppe
      state: 'on'
  action:
  - service: script.turn_on
    entity_id:  script.nattmodus_oppe_av