- alias: nattlys av hverdag hverdag
  trigger:
  - platform: time
    at: '06:15:00'
  - platform: homeassistant
    event: start
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.workday_today
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.nattlys_isabell
      brightness: 20
      rgb_color: 255,255,153
  - service: light.turn_on
    data:
      entity_id: light.nattlys_aleksander
      brightness: 20
      rgb_color: 255,255,153

- alias: nattlys av helg
  trigger:
  - platform: time
    at: '06:30:00'
  - platform: homeassistant
    event: start
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.workday_today
      state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.nattlys_isabell
      brightness: 20
      rgb_color: 255,255,153
  - service: light.turn_on
    data:
      entity_id: light.nattlys_aleksander
      brightness: 20
      rgb_color: 255,255,153