- alias: "Varsel lys offline"
  trigger:
  - platform: state
    entity_id:
    - light.gang_tak
    - light.kjokken_tak1
    - light.kjokken_tak2
    - light.kjokken_tak3
    - light.kjokken_tak4
    - light.kjokken_tak5
    - light.gangoppe1
    - light.gangoppe2
    - light.lampekjeller
    - light.pyntelampe
    - light.sofa1
    - light.sofa3
    - light.sofa2
    - light.spisebord
    - light.ute1
    - light.ute2
    - light.ute3
    to: 'unavailable'
    for:
      seconds: 120
  action:
    service: notify.pk
    data_template:
      title: "Lys er offline"
      message: "{{ trigger.to_state.attributes.friendly_name }} er offline"
