- alias: Stue natt ukedag
  trigger:
  - platform: time
    at: '22:00:00'
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    after: '22:00:00'
    before: '10:00:00'
  - condition: state
    entity_id: binary_sensor.workday_tomorrow
    state: 'on'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.stue_termostat
      temperature: "{{ states.input_number.stue_natt_temperatur.state | float }}"

- alias: Stue natt helg
  trigger:
  - platform: time
    at: '23:30:00'
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    after: '23:30:00'
    before: '08:30:00'
  - condition: state
    entity_id: binary_sensor.workday_tomorrow
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.stue_termostat
      temperature: "{{ states.input_number.stue_natt_temperatur.state | float }}"

- alias: Stue morgen ukedag
  trigger:
  - platform: time
    at: '07:00:00'
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    after: '07:00:00'
    before: '14:00:00'
  - condition: state
    entity_id: 'binary_sensor.workday_today'
    state: 'on'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.stue_termostat
      temperature: "{{ states.input_number.stue_morgen_temperatur.state | float }}"

- alias: Stue ettermiddag ukedag
  trigger:
  - platform: time
    at: '15:00:00'
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    after: '15:00:00'
    before: '22:00:00'
  - condition: state
    entity_id: 'binary_sensor.workday_today'
    state: 'on'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.stue_termostat
      temperature: "{{ states.input_number.stue_dagtid_temperatur.state | float }}"

- alias: Stue morgen helg
  trigger:
  - platform: time
    at: '08:30:00'
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    after: '08:30:00'
    before: '22:00:00'
  - condition: state
    entity_id: 'binary_sensor.workday_today'
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.stue_termostat
      temperature: "{{ states.input_number.stue_dagtid_temperatur.state | float }}"


# Door state changed
#
#- alias: Living room door opened
#  trigger:
#  - platform: state
#    entity_id: group.door_sensors_living_room_kitchen
#    to: 'on'
#    for:
#      seconds: 30
#  action:
#  - service: climate.set_operation_mode
#    data:
#      entity_id: climate.stue_termostat
#      operation_mode: 'off'
#
#- alias: Living room door closed
#  trigger:
#  - platform: state
#    entity_id: group.door_sensors_living_room_kitchen
#    to: 'off'
#    for:
#      minutes: 2
#  action:
#  - service: climate.set_operation_mode
#    data:
#      entity_id: climate.stue_termostat
#      operation_mode: 'heat'