- alias: DoorOpen
  trigger:
    platform: state
    entity_id: sensor.sensative_strips_access_control
    from: '22'
    to: '23'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.pk
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.trine
      state: 'not_home'
  action:
    service: notify.pk
    data_template:
      title: "Dør endret"
      message: "Døren er {% if is_state('sensor.sensative_strips_access_control', '22') %}åpen{% else %}lukket{% endif %}!"

- alias: DoorClosed
  trigger:
    platform: state
    entity_id: sensor.sensative_strips_access_control
    from: '23'
    to: '22'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.samsungs8
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.trine
      state: 'not_home'
  action:
    service: notify.pk
    data_template:
      title: "Dør endret"
      message: "Døren er {% if is_state('sensor.sensative_strips_access_control', '22') %}åpen{% else %}lukket{% endif %}!"

